#!/usr/bin/env python3
"""Config-level verification + full-matrix ping test for the PMUN topology.

Reads packet-builder/output/pmun_topology.xml (generated by pktgen.py) as the
artifact under test and device-configs/*.txt as the intent source, then:

  1. validates every PC/server address plan (complete fields, unique IPs,
     gateways on-subnet, DHCP-pool conformance of every seeded lease),
  2. rebuilds the per-VLAN broadcast domains from the .pkt wiring plus the
     switch/trunk/router-on-a-stick configs and proves each PC reaches its
     gateway inside its VLAN,
  3. rebuilds the router adjacency graph from shared subnets and checks OSPF
     coverage plus the border default route and ISP return route,
  4. simulates a ping between EVERY ordered pair of end hosts (PCs and
     servers, including ISP-DNS across the border) and reports pass/fail.

Exit code 0 only if everything passes. Pure stdlib.

Usage: python3 pingtest.py [xml_path]
"""

import os
import re
import sys
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
CFG = os.path.join(HERE, "..", "device-configs")

FAILURES = []


def check(cond, label):
    print("  [%s] %s" % ("PASS" if cond else "FAIL", label))
    if not cond:
        FAILURES.append(label)
    return cond


# --------------------------------------------------------------------------
# IOS config parsing
# --------------------------------------------------------------------------

def ios_interfaces(text):
    """interface name -> {ip, mask}."""
    out = {}
    cur = None
    for line in text.splitlines():
        m = re.match(r"^interface (\S+)", line)
        if m:
            cur = m.group(1)
            out.setdefault(cur, {"ip": None, "mask": None})
            continue
        m = re.match(r"^\s+ip address (\S+) (\S+)", line)
        if m and cur:
            out[cur]["ip"], out[cur]["mask"] = m.group(1), m.group(2)
    return out


def ospf_networks(text):
    nets = []
    in_ospf = False
    for line in text.splitlines():
        if re.match(r"^router ospf", line):
            in_ospf = True
        elif re.match(r"^\S", line):
            in_ospf = False
        m = re.match(r"^\s+network (\S+) (\S+) area (\S+)", line)
        if m and in_ospf:
            nets.append((m.group(1), m.group(2), m.group(3)))
    return nets


def dhcp_pools(text):
    pools = []
    excluded = []
    for line in text.splitlines():
        m = re.match(r"^ip dhcp excluded-address (\S+)(?: (\S+))?", line)
        if m:
            excluded.append((m.group(1), m.group(2) or m.group(1)))
    cur = None
    for line in text.splitlines():
        m = re.match(r"^ip dhcp pool (\S+)", line)
        if m:
            cur = {"name": m.group(1), "net": None, "mask": None,
                   "router": None, "dns": None}
            pools.append(cur)
            continue
        if cur is None:
            continue
        if re.match(r"^\S", line):
            cur = None
            continue
        m = re.match(r"^\s+network (\S+) (\S+)", line)
        if m:
            cur["net"], cur["mask"] = m.group(1), m.group(2)
        m = re.match(r"^\s+default-router (\S+)", line)
        if m:
            cur["router"] = m.group(1)
        m = re.match(r"^\s+dns-server (\S+)", line)
        if m:
            cur["dns"] = m.group(1)
    for p in pools:
        p["excluded"] = excluded
    return pools


def _expand_range(spec):
    """`FastEthernet0/1-20`, `Gi0/1-2` -> [port names]."""
    m = re.match(r"^(\D+)(\d+)/(\d+)-(\d+)$", spec.strip())
    if m:
        pfx, slot, lo, hi = m.group(1), m.group(2), int(m.group(3)), \
            int(m.group(4))
        return ["%s%s/%d" % (pfx, slot, i) for i in range(lo, hi + 1)]
    return [spec.strip()]


def switch_ports(text):
    ports = {}
    cur = []
    for line in text.splitlines():
        m = re.match(r"^interface (?:range )?(\S+)", line)
        if m:
            cur = []
            for part in m.group(1).split(","):
                cur.extend(_expand_range(part))
            for name in cur:
                ports.setdefault(name, {"mode": "access", "vlans": {1}})
            continue
        if not cur:
            continue
        m = re.match(r"^\s+switchport mode (\S+)", line)
        if m:
            for name in cur:
                ports[name]["mode"] = m.group(1)
        m = re.match(r"^\s+switchport access vlan (\d+)", line)
        if m:
            for name in cur:
                ports[name]["vlans"] = {int(m.group(1))}
        m = re.match(r"^\s+switchport trunk allowed vlan (\S+)", line)
        if m:
            vlans = set()
            for part in m.group(1).split(","):
                if "-" in part:
                    lo, hi = part.split("-")
                    vlans |= set(range(int(lo), int(hi) + 1))
                else:
                    vlans.add(int(part))
            for name in cur:
                ports[name]["vlans"] = vlans
    return ports


def ip_int(s):
    a, b, c, d = (int(x) for x in s.split("."))
    return (a << 24) | (b << 16) | (c << 8) | d


def cidr_match(ip, net, wildcard):
    w = ip_int(wildcard)
    return (ip_int(ip) & ~w & 0xFFFFFFFF) == (ip_int(net) & ~w & 0xFFFFFFFF)


def same_subnet(a, b, mask):
    m = ip_int(mask)
    return (ip_int(a) & m) == (ip_int(b) & m)


# --------------------------------------------------------------------------
# artifact parsing
# --------------------------------------------------------------------------

def load_xml(path):
    root = ET.parse(path).getroot()
    net = root.find("NETWORK")
    devices = []
    for dev in net.find("DEVICES"):
        engine = dev.find("ENGINE")
        dtype = engine.findtext("TYPE").strip()
        kind = ("router" if dtype == "Router"
                else "switch" if dtype == "Switch"
                else "server" if dtype == "Server" else "pc")
        entry = {"name": engine.findtext("NAME"), "kind": kind,
                 "eth": {"ip": "", "mask": "", "gw": "", "dns": ""}}
        for port in engine.iter("PORT"):
            if port.findtext("TYPE") == "eCopperFastEthernet" and \
                    entry["kind"] in ("pc", "server"):
                g = lambda t: (port.findtext(t) or "").strip()
                entry["eth"] = {"ip": g("IP"), "mask": g("SUBNET"),
                                "gw": g("PORT_GATEWAY"), "dns": g("PORT_DNS")}
                break
        devices.append(entry)

    links = []
    for lk in net.find("LINKS"):
        cab = lk.find("CABLE")
        cports = [c.text for c in cab if c.tag == "PORT"]
        links.append({
            "type": lk.findtext("TYPE"),
            "from": int(cab.findtext("FROM")),
            "from_port": cports[0],
            "to": int(cab.findtext("TO")),
            "to_port": cports[1] if len(cports) > 1 else cports[0],
        })
    return devices, links


# --------------------------------------------------------------------------
# main verification
# --------------------------------------------------------------------------

def main(xml_path):
    devices, links = load_xml(xml_path)
    cfg_text = {}
    for fn in sorted(os.listdir(CFG)):
        if fn.endswith(".txt"):
            cfg_text[fn[:-4]] = open(os.path.join(CFG, fn),
                                     encoding="utf-8").read()
    routers = {n: t for n, t in cfg_text.items()
               if n.startswith(("R", "ISP"))}

    adj = {}
    for lk in links:
        adj.setdefault(lk["from"], []).append(lk)
        adj.setdefault(lk["to"], []).append(lk)

    def link_other(lk, didx):
        return (lk["to"], lk["to_port"]) if lk["from"] == didx \
            else (lk["from"], lk["from_port"])

    def port_vlans(name, port):
        """VLAN set carried by a switch/router-attached port, via config."""
        sp = switch_ports(cfg_text.get(name, ""))
        if port in sp:
            return sp[port]["vlans"]
        for iname, info in sp.items():
            if iname == port or port.startswith(iname):
                return info["vlans"]
        return None

    def gw_on_router(rname, port, vlan, want_gw):
        """Does router `rname` answer `want_gw` on physical `port`/vlan?"""
        for pname, pi in ios_interfaces(cfg_text.get(rname, "")).items():
            if not pi["ip"] or pi["ip"] != want_gw:
                continue
            base = pname.split(".")[0]
            norm = {"Gi": "GigabitEthernet", "Fa": "FastEthernet"}.get(
                base[:2], base)
            if pname == port or base == port or port.startswith(base) or \
                    base.startswith(port):
                if "." in pname:
                    try:
                        if int(pname.split(".")[1]) != vlan:
                            continue
                    except ValueError:
                        pass
                return True
        return False

    print("== 1. host addressing ==")
    hosts = [d for d in devices if d["kind"] in ("pc", "server")]
    seen_ips = set()
    addr_ok = True
    for h in hosts:
        e = h["eth"]
        filled = all(e[k] for k in ("ip", "mask", "gw", "dns"))
        uniq = e["ip"] and e["ip"] not in seen_ips
        seen_ips.add(e["ip"])
        addr_ok &= filled and uniq
        print("  [%s] %-12s %-15s/%s gw=%-13s dns=%s" % (
            "PASS" if filled and uniq else "FAIL", h["name"],
            e["ip"] or "?", e["mask"] or "?", e["gw"] or "?",
            e["dns"] or "?"))
    check(addr_ok, "every host has a complete, unique address")

    print("== 2. gateways exist and are on-subnet ==")
    gw_ok = True
    host_rtr = {}
    for h in hosts:
        found = None
        for rname, text in routers.items():
            for pi in ios_interfaces(text).values():
                if pi["ip"] == h["eth"]["gw"] and pi["mask"] and \
                        same_subnet(h["eth"]["ip"], pi["ip"], pi["mask"]):
                    found = rname
        gw_ok &= found is not None
        host_rtr[h["name"]] = found
    check(gw_ok, "each gateway IP exists on a router sharing the subnet")

    print("== 3. seeded leases conform to DHCP pools ==")
    pool_ok = True
    for h in [d for d in devices if d["kind"] == "pc"]:
        ip, gw, dns = h["eth"]["ip"], h["eth"]["gw"], h["eth"]["dns"]
        hit = None
        if ip and gw:
            for rname, text in routers.items():
                for pool in dhcp_pools(text):
                    if pool["net"] and \
                            same_subnet(ip, pool["net"], pool["mask"]) \
                            and pool["router"] == gw:
                        hit = (rname, pool)
        if hit is None:
            pool_ok = False
            print("  [FAIL] %-12s no pool covers %s (gw %s)" %
                  (h["name"], ip, gw))
            continue
        _, pool = hit
        excluded = any(ip_int(lo) <= ip_int(ip) <= ip_int(hi)
                       for lo, hi in pool["excluded"])
        good = not excluded and pool["dns"] == dns
        pool_ok &= good
        print("  [%s] %-12s %s in %s (%s)%s" % (
            "PASS" if good else "FAIL", h["name"], ip,
            pool["net"], pool["name"],
            " -- IN EXCLUDED RANGE" if excluded else ""))
    check(pool_ok, "all PC leases inside pools, outside exclusions")

    # union-find over raw links (L1 connectivity)
    parent = list(range(len(devices)))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for lk in links:
        ra, rb = find(lk["from"]), find(lk["to"])
        if ra != rb:
            parent[ra] = rb

    def access_vlan(hidx):
        for lk in adj.get(hidx, []):
            other, oport = link_other(lk, hidx)
            od = devices[other]
            if od["kind"] == "switch":
                vl = port_vlans(od["name"], oport)
                if vl and len(vl) == 1:
                    return sorted(vl)[0]
            if od["kind"] == "router":
                return None                  # direct attachment
            return access_vlan(other) if other != hidx else None
        return None

    def gateway_reachable(hidx, vlan, want_gw):
        """BFS from PC through switches that carry `vlan`; success when a
        router interface matching want_gw terminates the domain."""
        stack = [(hidx, None)]
        visited = set()
        while stack:
            didx, via_port = stack.pop()
            d = devices[didx]
            key = (didx, via_port)
            if key in visited:
                continue
            visited.add(key)
            if didx == hidx and via_port is None:
                for lk in adj.get(didx, []):
                    other, oport = link_other(lk, didx)
                    stack.append((other, oport))
                continue
            if d["kind"] == "switch":
                if via_port:
                    vl = port_vlans(d["name"], via_port)
                    if vl is None or vlan not in vl:
                        continue
                for lk in adj.get(didx, []):
                    other, oport = link_other(lk, didx)
                    myport = lk["from_port"] if lk["from"] == didx \
                        else lk["to_port"]
                    mvl = port_vlans(d["name"], myport)
                    if mvl is None or vlan in mvl:
                        stack.append((other, oport))
            elif d["kind"] == "router":
                if via_port and gw_on_router(d["name"], via_port, vlan,
                                             want_gw):
                    return True
        return False

    print("== 4. per-VLAN broadcast domains ==")
    l2_ok = True
    for h in [d for d in devices if d["kind"] == "pc"]:
        hidx = devices.index(h)
        vlan = access_vlan(hidx)
        if vlan is None:
            print("  [PASS] %-12s direct-attached on router LAN port"
                  % h["name"])
            continue
        okp = gateway_reachable(hidx, vlan, h["eth"]["gw"])
        l2_ok &= okp
        print("  [%s] %-12s VLAN %-2d -> gw %s" % (
            "PASS" if okp else "FAIL", h["name"], vlan, h["eth"]["gw"]))
    check(l2_ok, "every switched PC reaches its gateway inside its VLAN")

    print("== 5. router adjacency + OSPF coverage ==")
    rnames = [d["name"] for d in devices if d["kind"] == "router"]
    rparent = {r: r for r in rnames}

    def find_r(x):
        while rparent[x] != x:
            rparent[x] = rparent[rparent[x]]
            x = rparent[x]
        return x

    edges = 0
    for lk in links:
        a, b = devices[lk["from"]], devices[lk["to"]]
        if a["kind"] != "router" or b["kind"] != "router":
            continue
        ia = ios_interfaces(cfg_text.get(a["name"], "")).get(lk["from_port"])
        ib = ios_interfaces(cfg_text.get(b["name"], "")).get(lk["to_port"])
        if ia and ib and ia["ip"] and ib["ip"] and ia["mask"] == ib["mask"] \
                and same_subnet(ia["ip"], ib["ip"], ia["mask"]):
            edges += 1
            ra, rb = find_r(a["name"]), find_r(b["name"])
            if ra != rb:
                rparent[ra] = rb
    connected = len({find_r(r) for r in rnames}) == 1
    check(connected, "router graph connected (%d routed links)" % edges)

    ospf_ok = True
    for rname in rnames:
        if rname == "ISP-RTR":
            continue
        nets = ospf_networks(cfg_text[rname])
        for pname, pi in ios_interfaces(cfg_text[rname]).items():
            if not pi["ip"]:
                continue
            if rname == "R9-BORDER" and pname == "Serial0/0/1":
                continue          # WAN toward ISP: static/default, not OSPF
            if not any(cidr_match(pi["ip"], n, w) for n, w, _ in nets):
                ospf_ok = False
                print("  [FAIL] %s %s (%s) missing from OSPF" %
                      (rname, pname, pi["ip"]))
    check(ospf_ok, "every routed interface advertised into OSPF")

    print("== 6. border routing ==")
    r9 = cfg_text.get("R9-BORDER", "")
    isp = cfg_text.get("ISP-RTR", "")
    has_default = bool(re.search(r"^ip route 0\.0\.0\.0 0\.0\.0\.0\s+\S+",
                                 r9, re.M))
    has_return = bool(re.search(
        r"^ip route 10\.10\.0\.0\s+\S+\s+\S+", isp, re.M))
    isp_no_ospf = "router ospf" not in isp
    check(has_default, "R9 originates default route toward ISP")
    check(has_return, "ISP-RTR holds return route for internal ranges")
    check(isp_no_ospf, "ISP-RTR runs no OSPF process")

    print("== 7. full ping matrix ==")
    total = passed = 0
    fails = []

    def same_l2(a, b):
        va, vb = access_vlan(devices.index(a)), access_vlan(devices.index(b))
        return (va is not None and va == vb
                and find(devices.index(a)) == find(devices.index(b)))

    def reachable(ra, rb):
        if ra is None or rb is None:
            return False
        if "ISP" in (ra, rb):
            return has_default and has_return
        return find_r(ra) == find_r(rb)

    for a in hosts:
        for b in hosts:
            if a is b:
                continue
            total += 1
            if same_l2(a, b) or reachable(host_rtr[a["name"]],
                                          host_rtr[b["name"]]):
                passed += 1
            else:
                fails.append((a["name"], b["name"]))
    print("  pings passed: %d/%d" % (passed, total))
    for f in fails[:20]:
        print("  FAIL %s -> %s" % f)
    check(passed == total, "full-matrix connectivity")

    print()
    if FAILURES:
        print("RESULT: FAIL (%d checks)" % len(FAILURES))
        return 1
    print("RESULT: ALL CHECKS PASSED")
    return 0


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        HERE, "output", "pmun_topology.xml")
    sys.exit(main(path))
